
function myFunction() {
    let text;
    let firstname = prompt("What is the first initial of your first name? (no caps)");
    if (firstname == "a") firstname = "Hopscotch"
    else if (firstname == "b") firstname = "Belle"
    else if (firstname == "c") firstname = "Gidget"
    else if (firstname == "d") firstname = "Hibiscus"
    else if (firstname == "e") firstname = "Frogspawn"
    else if (firstname == "f") firstname = "Trixie"
    else if (firstname == "g") firstname = "Tad"
    else if (firstname == "h") firstname = "Artie"
    else if (firstname == "i") firstname = "Bumble"
    else if (firstname == "j") firstname = "Dominus Ranarum, Lord of All Frogs, Toads, and Amphibious Creatures"
    else if (firstname == "k") firstname = "Dart"
    else if (firstname == "l") firstname = "Jason"
    else if (firstname == "m") firstname = "Polliwogs"
    else if (firstname == "n") firstname = "Stool"
    else if (firstname == "o") firstname = "Bogart"
    else if (firstname == "p") firstname = "Croak"
    else if (firstname == "q") firstname = "Daphne"
    else if (firstname == "r") firstname = "Leap"
    else if (firstname == "s") firstname = "Lily Paddy"
    else if (firstname == "t") firstname = "Swamp"
    else if (firstname == "u") firstname = "Legs"
    else if (firstname == "v") firstname = "Jelly"
    else if (firstname == "w") firstname = "Pickle"
    else if (firstname == "x") firstname = "Fredo"
    else if (firstname == "y") firstname = "Kermit"
    else if (firstname == "z") firstname = "Bubble"
    else if (firstname == "") firstname = "Human"
    else if (firstname == null) firstname = "Human"
    let secondname = prompt("What is the first initial of your second name? (no caps)");
    if (secondname == "a") secondname = " Hopsworth"
    else if (secondname == "b") secondname = " Frug"
    else if (secondname == "c") secondname = " Algae"
    else if (secondname == "d") secondname = " Toes"
    else if (secondname == "e") secondname = " Toadsley"
    else if (secondname == "f") secondname = " Boioioioing"
    else if (secondname == "g") secondname = " Greenboi"
    else if (secondname == "h") secondname = " Slimeso"
    else if (secondname == "i") secondname = " Swampthing"
    else if (secondname == "j") secondname = " Prince"
    else if (secondname == "k") secondname = " Grenouilles"
    else if (secondname == "l") secondname = " Wartworth"
    else if (secondname == "m") secondname = " Webber"
    else if (secondname == "n") secondname = " Pole"
    else if (secondname == "o") secondname = " Flylicker"
    else if (secondname == "p") secondname = " Croakberg"
    else if (secondname == "q") secondname = " Poison"
    else if (secondname == "r") secondname = " Funderberker"
    else if (secondname == "s") secondname = " President"
    else if (secondname == "t") secondname = " Ribbiton"
    else if (secondname == "u") secondname = " Bar"
    else if (secondname == "v") secondname = " The Frog"
    else if (secondname == "w") secondname = " Ooze"
    else if (secondname == "x") secondname = " Pilkington"
    else if (secondname == "y") secondname = " Smooth"
    else if (secondname == "z") secondname = " Longtongue"
    else if (secondname == "" ) secondname = " Fleshhair"
    else if (secondname == null) secondname = " Fleshhair"
    alert("Your frog name is " + firstname + secondname + "!")
}

